.TH "bike_data" 3 "Thu Jul 7 2022" "Version v0.1" "Engine Data Logger (EDL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bike_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBig_rpm\fP"
.br
.ti -1c
.RI "int32_t \fBalt_rpm\fP"
.br
.ti -1c
.RI "float \fBspeed\fP"
.br
.ti -1c
.RI "uint32_t \fBodometer\fP"
.br
.ti -1c
.RI "uint32_t \fBtrip\fP"
.br
.ti -1c
.RI "float \fBsystemvoltage\fP"
.br
.ti -1c
.RI "float \fBbatteryvoltage\fP"
.br
.ti -1c
.RI "float \fBoil_temp\fP"
.br
.ti -1c
.RI "float \fBoil_pres\fP"
.br
.ti -1c
.RI "bool \fBblink_left\fP"
.br
.ti -1c
.RI "bool \fBblink_right\fP"
.br
.ti -1c
.RI "uint16_t \fBlambda\fP"
.br
.RI "Lambda\&. Fixed point number 2 places after decimal, 0\&.01 (divide by 100) "
.ti -1c
.RI "int \fBmap_kpa\fP"
.br
.ti -1c
.RI "int \fBtps_percent\fP"
.br
.ti -1c
.RI "bool \fBengineRunning\fP"
.br
.ti -1c
.RI "uint8_t \fBadvance1\fP"
.br
.ti -1c
.RI "uint8_t \fBadvance2\fP"
.br
.ti -1c
.RI "uint8_t \fBadvance3\fP"
.br
.ti -1c
.RI "uint8_t \fBadvance4\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine Data Logger (EDL) from the source code\&.
