.TH "deprecated" 3 "Mon Jul 18 2022" "Version v0.1" "Engine Data Logger (EDL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBMember \fBcmdline_parser2\fP (int argc, char **argv, struct \fBgengetopt_args_info\fP *args_info, int override, int initialize, int check_required)\fP" 1c
use \fBcmdline_parser_ext()\fP instead  
.IP "\fBMember \fBcmdline_parser_configfile\fP (const char *filename, struct \fBgengetopt_args_info\fP *args_info, int override, int initialize, int check_required)\fP" 1c
use \fBcmdline_parser_config_file()\fP instead 
.PP

