.TH "EDL::AppBuffer::FLATBUFFERS_FINAL_CLASS" 3 "Mon Jul 18 2022" "Version v0.1" "Engine Data Logger (EDL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EDL::AppBuffer::FLATBUFFERS_FINAL_CLASS
.SH SYNOPSIS
.br
.PP
.PP
Inherits flatbuffers::Table\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBBikeT\fP \fBNativeTableType\fP"
.br
.ti -1c
.RI "typedef \fBBikeBuilder\fP \fBBuilder\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int32_t \fBrpm\fP () const"
.br
.ti -1c
.RI "float \fBspeed\fP () const"
.br
.ti -1c
.RI "uint32_t \fBodometer\fP () const"
.br
.ti -1c
.RI "uint32_t \fBtrip\fP () const"
.br
.ti -1c
.RI "float \fBsystemvoltage\fP () const"
.br
.ti -1c
.RI "float \fBbatteryvoltage\fP () const"
.br
.ti -1c
.RI "float \fBoil_temp\fP () const"
.br
.ti -1c
.RI "bool \fBblink_left\fP () const"
.br
.ti -1c
.RI "bool \fBblink_right\fP () const"
.br
.ti -1c
.RI "uint16_t \fBlambda\fP () const"
.br
.ti -1c
.RI "int32_t \fBmap_kpa\fP () const"
.br
.ti -1c
.RI "float \fBoil_pres\fP () const"
.br
.ti -1c
.RI "int32_t \fBalt_rpm\fP () const"
.br
.ti -1c
.RI "const flatbuffers::String * \fBgear\fP () const"
.br
.ti -1c
.RI "bool \fBVerify\fP (flatbuffers::Verifier &verifier) const"
.br
.ti -1c
.RI "\fBBikeT\fP * \fBUnPack\fP (const flatbuffers::resolver_function_t *_resolver=nullptr) const"
.br
.ti -1c
.RI "void \fBUnPackTo\fP (\fBBikeT\fP *_o, const flatbuffers::resolver_function_t *_resolver=nullptr) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static flatbuffers::Offset< Bike > \fBPack\fP (flatbuffers::FlatBufferBuilder &_fbb, const \fBBikeT\fP *_o, const flatbuffers::rehasher_function_t *_rehasher=nullptr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine Data Logger (EDL) from the source code\&.
