.TH "EDL::AppBuffer::BikeT" 3 "Mon Jul 18 2022" "Version v0.1" "Engine Data Logger (EDL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EDL::AppBuffer::BikeT
.SH SYNOPSIS
.br
.PP
.PP
Inherits flatbuffers::NativeTable\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Bike \fBTableType\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBrpm\fP"
.br
.ti -1c
.RI "float \fBspeed\fP"
.br
.ti -1c
.RI "uint32_t \fBodometer\fP"
.br
.ti -1c
.RI "uint32_t \fBtrip\fP"
.br
.ti -1c
.RI "float \fBsystemvoltage\fP"
.br
.ti -1c
.RI "float \fBbatteryvoltage\fP"
.br
.ti -1c
.RI "float \fBoil_temp\fP"
.br
.ti -1c
.RI "bool \fBblink_left\fP"
.br
.ti -1c
.RI "bool \fBblink_right\fP"
.br
.ti -1c
.RI "uint16_t \fBlambda\fP"
.br
.ti -1c
.RI "int32_t \fBmap_kpa\fP"
.br
.ti -1c
.RI "float \fBoil_pres\fP"
.br
.ti -1c
.RI "int32_t \fBalt_rpm\fP"
.br
.ti -1c
.RI "std::string \fBgear\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine Data Logger (EDL) from the source code\&.
