.TH "engine_data" 3 "Thu Jul 7 2022" "Version v0.1" "Engine Data Logger (EDL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBrpm\fP = 0"
.br
.ti -1c
.RI "float \fBbatteryVoltage\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBtemp_oil\fP = 0"
.br
.ti -1c
.RI "float \fBpres_oil\fP = 0"
.br
.ti -1c
.RI "float \fBspeed\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBodometer\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBtrip\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine Data Logger (EDL) from the source code\&.
