.TH "fc_data" 3 "Mon Jul 18 2022" "Version v0.1" "Engine Data Logger (EDL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBserialCmdD\fP = 0"
.br
.ti -1c
.RI "uint8_t \fBserialCmdB\fP = 0"
.br
.ti -1c
.RI "uint8_t \fBserialCmdC\fP = 0"
.br
.ti -1c
.RI "uint8_t \fBserialCmdA\fP = 0"
.br
.ti -1c
.RI "uint8_t \fBinputCmdD\fP = 0"
.br
.ti -1c
.RI "uint8_t \fBinputCmdC\fP = 0"
.br
.ti -1c
.RI "float \fBsystemVoltage\fP = 0\&.0"
.br
.ti -1c
.RI "bool \fBbrake_on\fP = false"
.br
.ti -1c
.RI "bool \fBhorn_on\fP = false"
.br
.ti -1c
.RI "bool \fBleft_on\fP = false"
.br
.ti -1c
.RI "bool \fBright_on\fP = false"
.br
.ti -1c
.RI "bool \fBhigh_on\fP = false"
.br
.ti -1c
.RI "bool \fBkill_on\fP = false"
.br
.ti -1c
.RI "bool \fBclutch_disengaged\fP = false"
.br
.ti -1c
.RI "bool \fBkickstand_up\fP = false"
.br
.ti -1c
.RI "bool \fBin_neutral\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine Data Logger (EDL) from the source code\&.
