.TH "gps_gps_stat_t" 3 "Mon Jul 18 2022" "Version v0.1" "Engine Data Logger (EDL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gps_gps_stat_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gps\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBactive_satellites\fP"
.br
.ti -1c
.RI "uint8_t \fBtype\fP"
.br
.ti -1c
.RI "uint8_t \fBvisible_satellites\fP"
.br
.ti -1c
.RI "uint16_t \fBpdop\fP"
.br
.ti -1c
.RI "uint16_t \fBhdop\fP"
.br
.ti -1c
.RI "uint16_t \fBvdop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message GPS_Stat\&.
.PP
All signal values are as on the CAN bus\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint8_t gps_gps_stat_t::active_satellites"
Range: 0\&.\&.63 (0\&.\&.63 -) Scale: 1 Offset: 0 
.SS "uint16_t gps_gps_stat_t::hdop"
Range: 0\&.\&.99990 (0\&.\&.9999 m) Scale: 0\&.1 Offset: 0 
.SS "uint16_t gps_gps_stat_t::pdop"
Range: 0\&.\&.99990 (0\&.\&.9999 m) Scale: 0\&.1 Offset: 0 
.SS "uint8_t gps_gps_stat_t::type"
Range: 0\&.\&.15 (0\&.\&.15 -) Scale: 1 Offset: 0 
.SS "uint16_t gps_gps_stat_t::vdop"
Range: 0\&.\&.99990 (0\&.\&.9999 m) Scale: 0\&.1 Offset: 0 
.SS "uint8_t gps_gps_stat_t::visible_satellites"
Range: 0\&.\&.63 (0\&.\&.63 -) Scale: 1 Offset: 0 

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine Data Logger (EDL) from the source code\&.
