.TH "gps_gps_loc_t" 3 "Mon Jul 18 2022" "Version v0.1" "Engine Data Logger (EDL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gps_gps_loc_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gps\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBlat_decimal_degrees\fP"
.br
.ti -1c
.RI "uint32_t \fBlong_decimal_degrees\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message GPS_Loc\&.
.PP
All signal values are as on the CAN bus\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint32_t gps_gps_loc_t::lat_decimal_degrees"
Range: 0\&.\&.180000000 (-90\&.\&.90 Deg) Scale: 1e-06 Offset: -90 
.SS "uint32_t gps_gps_loc_t::long_decimal_degrees"
Range: 0\&.\&.360000000 (-180\&.\&.180 Deg) Scale: 1e-06 Offset: -180 

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine Data Logger (EDL) from the source code\&.
