.TH "gps_gps_time_t" 3 "Thu Jul 7 2022" "Version v0.1" "Engine Data Logger (EDL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gps_gps_time_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gps\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBday\fP"
.br
.ti -1c
.RI "uint8_t \fBmonth\fP"
.br
.ti -1c
.RI "uint16_t \fByear\fP"
.br
.ti -1c
.RI "uint8_t \fBhour\fP"
.br
.ti -1c
.RI "uint8_t \fBminute\fP"
.br
.ti -1c
.RI "uint8_t \fBsecond\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message GPS_Time\&.
.PP
All signal values are as on the CAN bus\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint8_t gps_gps_time_t::day"
Range: 1\&.\&.31 (1\&.\&.31 -) Scale: 1 Offset: 0 
.SS "uint8_t gps_gps_time_t::hour"
Range: 0\&.\&.23 (0\&.\&.23 -) Scale: 1 Offset: 0 
.SS "uint8_t gps_gps_time_t::minute"
Range: 0\&.\&.59 (0\&.\&.59 -) Scale: 1 Offset: 0 
.SS "uint8_t gps_gps_time_t::month"
Range: 1\&.\&.12 (1\&.\&.12 -) Scale: 1 Offset: 0 
.SS "uint8_t gps_gps_time_t::second"
Range: 0\&.\&.59 (0\&.\&.59 -) Scale: 1 Offset: 0 
.SS "uint16_t gps_gps_time_t::year"
Range: 1\&.\&.65535 (1\&.\&.65535 -) Scale: 1 Offset: 0 

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine Data Logger (EDL) from the source code\&.
