.TH "ignitech_can_ignitech_wb_2_t" 3 "Mon Jul 18 2022" "Version v0.1" "Engine Data Logger (EDL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ignitech_can_ignitech_wb_2_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ignitech_can\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBlambda\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Ignitech_WB_2\&.
.PP
All signal values are as on the CAN bus\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint16_t ignitech_can_ignitech_wb_2_t::lambda"
Range: 0\&.\&.10000 (0\&.\&.100\&.00 -) Scale: 0\&.01 Offset: 0 

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine Data Logger (EDL) from the source code\&.
