.TH "imu_can_body_accel_t" 3 "Mon Jul 18 2022" "Version v0.1" "Engine Data Logger (EDL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imu_can_body_accel_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <imu_can\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBacc_x\fP"
.br
.ti -1c
.RI "uint16_t \fBacc_y\fP"
.br
.ti -1c
.RI "uint16_t \fBacc_z\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message BODY_ACCEL\&.
.PP
All signal values are as on the CAN bus\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint16_t imu_can_body_accel_t::acc_x"
Range: 0\&.\&.40000 (-20\&.\&.20 m/s2) Scale: 0\&.001 Offset: -20 
.SS "uint16_t imu_can_body_accel_t::acc_y"
Range: 0\&.\&.40000 (-20\&.\&.20 m/s2) Scale: 0\&.001 Offset: -20 
.SS "uint16_t imu_can_body_accel_t::acc_z"
Range: 0\&.\&.40000 (-20\&.\&.20 m/s2) Scale: 0\&.001 Offset: -20 

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine Data Logger (EDL) from the source code\&.
