.TH "imu_can_body_position_t" 3 "Thu Jul 7 2022" "Version v0.1" "Engine Data Logger (EDL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imu_can_body_position_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <imu_can\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBroll_angle\fP"
.br
.ti -1c
.RI "uint16_t \fBpitch_angle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message BODY_POSITION\&.
.PP
All signal values are as on the CAN bus\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint16_t imu_can_body_position_t::pitch_angle"
Range: 0\&.\&.3600 (-180\&.\&.180 deg) Scale: 0\&.1 Offset: -180 
.SS "uint16_t imu_can_body_position_t::roll_angle"
Range: 0\&.\&.3600 (-180\&.\&.180 deg) Scale: 0\&.1 Offset: -180 

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine Data Logger (EDL) from the source code\&.
