.TH "obd2_obd2_request_t" 3 "Mon Jul 18 2022" "Version v0.1" "Engine Data Logger (EDL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obd2_obd2_request_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <obd2\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBmode\fP"
.br
.ti -1c
.RI "uint8_t \fBpid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message OBD2_Request\&.
.PP
All signal values are as on the CAN bus\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint8_t obd2_obd2_request_t::mode"
Range: 0\&.\&.255 (0\&.\&.255 -) Scale: 1 Offset: 0 
.SS "uint8_t obd2_obd2_request_t::pid"
Range: 0\&.\&.255 (0\&.\&.255 -) Scale: 1 Offset: 0 

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine Data Logger (EDL) from the source code\&.
