.TH "src/powercalc.h" 3 "Mon Jul 18 2022" "Version v0.1" "Engine Data Logger (EDL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/powercalc.h \- Header file for power calculation functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sys/time\&.h>\fP
.br
\fC#include 'error_handling\&.h'\fP
.br
\fC#include 'definitions\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtrailing_average_power\fP (\fBbike_data\fP &log_data, int periods=20)"
.br
.ti -1c
.RI "int \fBtimeval_subtract\fP (struct timeval *result, struct timeval *x, struct timeval *y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file for power calculation functions\&. 


.SH "Function Documentation"
.PP 
.SS "int timeval_subtract (struct timeval * result, struct timeval * x, struct timeval * y)"
@Alexey Frunze https://stackoverflow.com/questions/15846762/timeval-subtract-explanation Shamelessly copied 
.SH "Author"
.PP 
Generated automatically by Doxygen for Engine Data Logger (EDL) from the source code\&.
