/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  gengetopt -C --output-dir=./src/ -i ./data/cmdline.ggo --func-name=cmdline_parser --conf-parser

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: " CMDLINE_PARSER_PACKAGE " [OPTION]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_detailed_help[] = {
  "  -h, --help                    Print help and exit",
  "      --detailed-help           Print help, including all details and hidden\n                                  options, and exit",
  "      --full-help               Print help, including hidden options, and exit",
  "  -V, --version                 Print version and exit",
  "  -c, --config-file=filename    Configuration file.",
  "  -o, --output-file=filename    Output file for CSV logging\n                                  (default=`/dev/null')",
  "  -G, --gpx-file=filename       Output file for GPX logging\n                                  (default=`/dev/null')",
  "  -d, --output-file-date        Insert date and time into output filename.",
  "      --output-file-format=format\n                                Format string of output CSV file",
  "  \n  		Comma-separated list of loggable values. Valid items are:\n  	rpm, ig_rpm, alt_rpm, speed, map_kpa, tps_percent, odometer, trip,\n  	systemvoltage, batteryvoltage, oil_temp, oil_pres, lambda,\n  	enginerunning(bool), blink_left(bool), blink_right(bool), advance1,\n  	advance2, advance3, advance4, yaw, pitch, roll, acc_forward, acc_side,\n  	acc_vert, power, latitude, longitude, altitude, gps_speed, gps_heading,\n  	gpsfix, pdop, hdop, vdop, satellitesInView, satellitesInUse, gpstime(UTC),\n  	and time(current date/time)\n  	",
  "  -g, --gear-ratios=STRING      RPM/Speed ratios. Comma separated. (Eg. -g\n                                  \"175,122,95,78,67\")",
  "  -W, --weight=kg               Weight of vehicle, in kg, to use for\n                                  calculations.  (default=`300')",
  "  -v, --v                       Verbose output. Specify multiple times for\n                                  increasing verbosity.",
  "      --verbose=VERBOSITY       Set level of verbosity explicitly. \n                                  (Overrides -v)\n                                    (possible values=\"NONE\", \"ERROR\",\n                                  \"WARN\", \"INFO\", \"DEBUG\"\n                                  default=`ERROR')",
  "  -q, --quiet                   Suppress output. Same as --verbose=NONE\n                                  (Overrides both -v and --verbose)",
  "\nDevice Interfaces:",
  "  -f, --front-controls=device   Front controls device",
  "  -i, --ignitech=device         Ignitech ignition device",
  "  -l, --lc2=device              Innovate LC-2 device",
  "      --lc2-delay=seconds       Delay before powering up LC-2.  (default=`15')",
  "      --lc2-pin=INT             GPIO pin that controls power for LC-2\n                                  (default=`26')",
  "  -s, --sleepy=device           I2C device to communicate with Sleepy Pi.",
  "      --sleepy-addr=0xXX        Address for Sleepy Pi.  (default=`0x04')",
  "      --can=device              CAN device to bind to. CAN disabled if not set.",
  "\nIgnitech specific options:",
  "      --ignitech-dump-file=filename\n                                File to dump raw responses from Ignitech",
  "      --ignitech-servo-as-iap   Treat servo reading as IAP. Requires\n                                  calibration options.  (default=off)",
  "      --ignitech-sai-low=INT    Low kpa reading. Eg: 21",
  "      --ignitech-sai-low-mv=INT Low mv value. Eg: 708",
  "      --ignitech-sai-high=INT   High kpa reading. Eg: 102",
  "      --ignitech-sai-high-mv=INT\n                                High mv value. Eg: 4252",
  "\nCAN device tweaks:",
  "      --mount-offset-roll=FLOAT Offset to zero imu reading",
  "      --mount-offset-pitch=FLOAT\n                                Offset to zero imu reading",
  "      --roll-pitch-swap         Swap roll and pitch. Used depending on physical\n                                  sensor orientation.  (default=off)",
  "      --test-mode=INT           Secret test mode. Does not continue running\n                                  (default=`0')",
    0
};
static void
init_full_help_array(void)
{
  gengetopt_args_info_full_help[0] = gengetopt_args_info_detailed_help[0];
  gengetopt_args_info_full_help[1] = gengetopt_args_info_detailed_help[1];
  gengetopt_args_info_full_help[2] = gengetopt_args_info_detailed_help[2];
  gengetopt_args_info_full_help[3] = gengetopt_args_info_detailed_help[3];
  gengetopt_args_info_full_help[4] = gengetopt_args_info_detailed_help[4];
  gengetopt_args_info_full_help[5] = gengetopt_args_info_detailed_help[5];
  gengetopt_args_info_full_help[6] = gengetopt_args_info_detailed_help[6];
  gengetopt_args_info_full_help[7] = gengetopt_args_info_detailed_help[7];
  gengetopt_args_info_full_help[8] = gengetopt_args_info_detailed_help[8];
  gengetopt_args_info_full_help[9] = gengetopt_args_info_detailed_help[10];
  gengetopt_args_info_full_help[10] = gengetopt_args_info_detailed_help[11];
  gengetopt_args_info_full_help[11] = gengetopt_args_info_detailed_help[12];
  gengetopt_args_info_full_help[12] = gengetopt_args_info_detailed_help[13];
  gengetopt_args_info_full_help[13] = gengetopt_args_info_detailed_help[14];
  gengetopt_args_info_full_help[14] = gengetopt_args_info_detailed_help[15];
  gengetopt_args_info_full_help[15] = gengetopt_args_info_detailed_help[16];
  gengetopt_args_info_full_help[16] = gengetopt_args_info_detailed_help[17];
  gengetopt_args_info_full_help[17] = gengetopt_args_info_detailed_help[18];
  gengetopt_args_info_full_help[18] = gengetopt_args_info_detailed_help[19];
  gengetopt_args_info_full_help[19] = gengetopt_args_info_detailed_help[20];
  gengetopt_args_info_full_help[20] = gengetopt_args_info_detailed_help[21];
  gengetopt_args_info_full_help[21] = gengetopt_args_info_detailed_help[22];
  gengetopt_args_info_full_help[22] = gengetopt_args_info_detailed_help[23];
  gengetopt_args_info_full_help[23] = gengetopt_args_info_detailed_help[24];
  gengetopt_args_info_full_help[24] = gengetopt_args_info_detailed_help[25];
  gengetopt_args_info_full_help[25] = gengetopt_args_info_detailed_help[26];
  gengetopt_args_info_full_help[26] = gengetopt_args_info_detailed_help[27];
  gengetopt_args_info_full_help[27] = gengetopt_args_info_detailed_help[28];
  gengetopt_args_info_full_help[28] = gengetopt_args_info_detailed_help[29];
  gengetopt_args_info_full_help[29] = gengetopt_args_info_detailed_help[30];
  gengetopt_args_info_full_help[30] = gengetopt_args_info_detailed_help[31];
  gengetopt_args_info_full_help[31] = gengetopt_args_info_detailed_help[32];
  gengetopt_args_info_full_help[32] = gengetopt_args_info_detailed_help[33];
  gengetopt_args_info_full_help[33] = gengetopt_args_info_detailed_help[34];
  gengetopt_args_info_full_help[34] = gengetopt_args_info_detailed_help[35];
  gengetopt_args_info_full_help[35] = 0; 
  
}

const char *gengetopt_args_info_full_help[36];

static void
init_help_array(void)
{
  gengetopt_args_info_help[0] = gengetopt_args_info_detailed_help[0];
  gengetopt_args_info_help[1] = gengetopt_args_info_detailed_help[1];
  gengetopt_args_info_help[2] = gengetopt_args_info_detailed_help[2];
  gengetopt_args_info_help[3] = gengetopt_args_info_detailed_help[3];
  gengetopt_args_info_help[4] = gengetopt_args_info_detailed_help[4];
  gengetopt_args_info_help[5] = gengetopt_args_info_detailed_help[5];
  gengetopt_args_info_help[6] = gengetopt_args_info_detailed_help[6];
  gengetopt_args_info_help[7] = gengetopt_args_info_detailed_help[7];
  gengetopt_args_info_help[8] = gengetopt_args_info_detailed_help[8];
  gengetopt_args_info_help[9] = gengetopt_args_info_detailed_help[10];
  gengetopt_args_info_help[10] = gengetopt_args_info_detailed_help[11];
  gengetopt_args_info_help[11] = gengetopt_args_info_detailed_help[12];
  gengetopt_args_info_help[12] = gengetopt_args_info_detailed_help[13];
  gengetopt_args_info_help[13] = gengetopt_args_info_detailed_help[14];
  gengetopt_args_info_help[14] = gengetopt_args_info_detailed_help[15];
  gengetopt_args_info_help[15] = gengetopt_args_info_detailed_help[16];
  gengetopt_args_info_help[16] = gengetopt_args_info_detailed_help[17];
  gengetopt_args_info_help[17] = gengetopt_args_info_detailed_help[18];
  gengetopt_args_info_help[18] = gengetopt_args_info_detailed_help[19];
  gengetopt_args_info_help[19] = gengetopt_args_info_detailed_help[20];
  gengetopt_args_info_help[20] = gengetopt_args_info_detailed_help[21];
  gengetopt_args_info_help[21] = gengetopt_args_info_detailed_help[22];
  gengetopt_args_info_help[22] = gengetopt_args_info_detailed_help[23];
  gengetopt_args_info_help[23] = gengetopt_args_info_detailed_help[24];
  gengetopt_args_info_help[24] = gengetopt_args_info_detailed_help[25];
  gengetopt_args_info_help[25] = gengetopt_args_info_detailed_help[26];
  gengetopt_args_info_help[26] = gengetopt_args_info_detailed_help[27];
  gengetopt_args_info_help[27] = gengetopt_args_info_detailed_help[28];
  gengetopt_args_info_help[28] = gengetopt_args_info_detailed_help[29];
  gengetopt_args_info_help[29] = gengetopt_args_info_detailed_help[30];
  gengetopt_args_info_help[30] = gengetopt_args_info_detailed_help[31];
  gengetopt_args_info_help[31] = gengetopt_args_info_detailed_help[32];
  gengetopt_args_info_help[32] = gengetopt_args_info_detailed_help[33];
  gengetopt_args_info_help[33] = gengetopt_args_info_detailed_help[34];
  gengetopt_args_info_help[34] = 0; 
  
}

const char *gengetopt_args_info_help[35];

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_FLOAT
  , ARG_ENUM
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);
struct line_list
{
  char * string_arg;
  struct line_list * next;
};

static struct line_list *cmd_line_list = 0;
static struct line_list *cmd_line_list_tmp = 0;

static void
free_cmd_list(void)
{
  /* free the list of a previous call */
  if (cmd_line_list)
    {
      while (cmd_line_list) {
        cmd_line_list_tmp = cmd_line_list;
        cmd_line_list = cmd_line_list->next;
        free (cmd_line_list_tmp->string_arg);
        free (cmd_line_list_tmp);
      }
    }
}


const char *cmdline_parser_verbose_values[] = {"NONE", "ERROR", "WARN", "INFO", "DEBUG", 0}; /*< Possible values for verbose. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->detailed_help_given = 0 ;
  args_info->full_help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->config_file_given = 0 ;
  args_info->output_file_given = 0 ;
  args_info->gpx_file_given = 0 ;
  args_info->output_file_date_given = 0 ;
  args_info->output_file_format_given = 0 ;
  args_info->gear_ratios_given = 0 ;
  args_info->weight_given = 0 ;
  args_info->v_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->quiet_given = 0 ;
  args_info->front_controls_given = 0 ;
  args_info->ignitech_given = 0 ;
  args_info->lc2_given = 0 ;
  args_info->lc2_delay_given = 0 ;
  args_info->lc2_pin_given = 0 ;
  args_info->sleepy_given = 0 ;
  args_info->sleepy_addr_given = 0 ;
  args_info->can_given = 0 ;
  args_info->ignitech_dump_file_given = 0 ;
  args_info->ignitech_servo_as_iap_given = 0 ;
  args_info->ignitech_sai_low_given = 0 ;
  args_info->ignitech_sai_low_mv_given = 0 ;
  args_info->ignitech_sai_high_given = 0 ;
  args_info->ignitech_sai_high_mv_given = 0 ;
  args_info->mount_offset_roll_given = 0 ;
  args_info->mount_offset_pitch_given = 0 ;
  args_info->roll_pitch_swap_given = 0 ;
  args_info->test_mode_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->config_file_arg = NULL;
  args_info->config_file_orig = NULL;
  args_info->output_file_arg = gengetopt_strdup ("/dev/null");
  args_info->output_file_orig = NULL;
  args_info->gpx_file_arg = gengetopt_strdup ("/dev/null");
  args_info->gpx_file_orig = NULL;
  args_info->output_file_format_arg = NULL;
  args_info->output_file_format_orig = NULL;
  args_info->gear_ratios_arg = NULL;
  args_info->gear_ratios_orig = NULL;
  args_info->weight_arg = 300;
  args_info->weight_orig = NULL;
  args_info->verbose_arg = verbose_arg_ERROR;
  args_info->verbose_orig = NULL;
  args_info->front_controls_arg = NULL;
  args_info->front_controls_orig = NULL;
  args_info->ignitech_arg = NULL;
  args_info->ignitech_orig = NULL;
  args_info->lc2_arg = NULL;
  args_info->lc2_orig = NULL;
  args_info->lc2_delay_arg = 15;
  args_info->lc2_delay_orig = NULL;
  args_info->lc2_pin_arg = 26;
  args_info->lc2_pin_orig = NULL;
  args_info->sleepy_arg = NULL;
  args_info->sleepy_orig = NULL;
  args_info->sleepy_addr_arg = gengetopt_strdup ("0x04");
  args_info->sleepy_addr_orig = NULL;
  args_info->can_arg = NULL;
  args_info->can_orig = NULL;
  args_info->ignitech_dump_file_arg = NULL;
  args_info->ignitech_dump_file_orig = NULL;
  args_info->ignitech_servo_as_iap_flag = 0;
  args_info->ignitech_sai_low_orig = NULL;
  args_info->ignitech_sai_low_mv_orig = NULL;
  args_info->ignitech_sai_high_orig = NULL;
  args_info->ignitech_sai_high_mv_orig = NULL;
  args_info->mount_offset_roll_orig = NULL;
  args_info->mount_offset_pitch_orig = NULL;
  args_info->roll_pitch_swap_flag = 0;
  args_info->test_mode_arg = 0;
  args_info->test_mode_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{
  init_full_help_array(); 
  init_help_array(); 
  args_info->help_help = gengetopt_args_info_detailed_help[0] ;
  args_info->detailed_help_help = gengetopt_args_info_detailed_help[1] ;
  args_info->full_help_help = gengetopt_args_info_detailed_help[2] ;
  args_info->version_help = gengetopt_args_info_detailed_help[3] ;
  args_info->config_file_help = gengetopt_args_info_detailed_help[4] ;
  args_info->output_file_help = gengetopt_args_info_detailed_help[5] ;
  args_info->gpx_file_help = gengetopt_args_info_detailed_help[6] ;
  args_info->output_file_date_help = gengetopt_args_info_detailed_help[7] ;
  args_info->output_file_format_help = gengetopt_args_info_detailed_help[8] ;
  args_info->gear_ratios_help = gengetopt_args_info_detailed_help[10] ;
  args_info->weight_help = gengetopt_args_info_detailed_help[11] ;
  args_info->v_help = gengetopt_args_info_detailed_help[12] ;
  args_info->v_min = 1;
  args_info->v_max = 3;
  args_info->verbose_help = gengetopt_args_info_detailed_help[13] ;
  args_info->quiet_help = gengetopt_args_info_detailed_help[14] ;
  args_info->front_controls_help = gengetopt_args_info_detailed_help[16] ;
  args_info->ignitech_help = gengetopt_args_info_detailed_help[17] ;
  args_info->lc2_help = gengetopt_args_info_detailed_help[18] ;
  args_info->lc2_delay_help = gengetopt_args_info_detailed_help[19] ;
  args_info->lc2_pin_help = gengetopt_args_info_detailed_help[20] ;
  args_info->sleepy_help = gengetopt_args_info_detailed_help[21] ;
  args_info->sleepy_addr_help = gengetopt_args_info_detailed_help[22] ;
  args_info->can_help = gengetopt_args_info_detailed_help[23] ;
  args_info->ignitech_dump_file_help = gengetopt_args_info_detailed_help[25] ;
  args_info->ignitech_servo_as_iap_help = gengetopt_args_info_detailed_help[26] ;
  args_info->ignitech_sai_low_help = gengetopt_args_info_detailed_help[27] ;
  args_info->ignitech_sai_low_mv_help = gengetopt_args_info_detailed_help[28] ;
  args_info->ignitech_sai_high_help = gengetopt_args_info_detailed_help[29] ;
  args_info->ignitech_sai_high_mv_help = gengetopt_args_info_detailed_help[30] ;
  args_info->mount_offset_roll_help = gengetopt_args_info_detailed_help[32] ;
  args_info->mount_offset_pitch_help = gengetopt_args_info_detailed_help[33] ;
  args_info->roll_pitch_swap_help = gengetopt_args_info_detailed_help[34] ;
  args_info->test_mode_help = gengetopt_args_info_detailed_help[35] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(gengetopt_args_info_purpose);
	size_t len_usage = strlen(gengetopt_args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", gengetopt_args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", gengetopt_args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(gengetopt_args_info_description) > 0) {
		printf("%s\n\n", gengetopt_args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_print_full_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_full_help[i])
    printf("%s\n", gengetopt_args_info_full_help[i++]);
}

void
cmdline_parser_print_detailed_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_detailed_help[i])
    printf("%s\n", gengetopt_args_info_detailed_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->config_file_arg));
  free_string_field (&(args_info->config_file_orig));
  free_string_field (&(args_info->output_file_arg));
  free_string_field (&(args_info->output_file_orig));
  free_string_field (&(args_info->gpx_file_arg));
  free_string_field (&(args_info->gpx_file_orig));
  free_string_field (&(args_info->output_file_format_arg));
  free_string_field (&(args_info->output_file_format_orig));
  free_string_field (&(args_info->gear_ratios_arg));
  free_string_field (&(args_info->gear_ratios_orig));
  free_string_field (&(args_info->weight_orig));
  free_string_field (&(args_info->verbose_orig));
  free_string_field (&(args_info->front_controls_arg));
  free_string_field (&(args_info->front_controls_orig));
  free_string_field (&(args_info->ignitech_arg));
  free_string_field (&(args_info->ignitech_orig));
  free_string_field (&(args_info->lc2_arg));
  free_string_field (&(args_info->lc2_orig));
  free_string_field (&(args_info->lc2_delay_orig));
  free_string_field (&(args_info->lc2_pin_orig));
  free_string_field (&(args_info->sleepy_arg));
  free_string_field (&(args_info->sleepy_orig));
  free_string_field (&(args_info->sleepy_addr_arg));
  free_string_field (&(args_info->sleepy_addr_orig));
  free_string_field (&(args_info->can_arg));
  free_string_field (&(args_info->can_orig));
  free_string_field (&(args_info->ignitech_dump_file_arg));
  free_string_field (&(args_info->ignitech_dump_file_orig));
  free_string_field (&(args_info->ignitech_sai_low_orig));
  free_string_field (&(args_info->ignitech_sai_low_mv_orig));
  free_string_field (&(args_info->ignitech_sai_high_orig));
  free_string_field (&(args_info->ignitech_sai_high_mv_orig));
  free_string_field (&(args_info->mount_offset_roll_orig));
  free_string_field (&(args_info->mount_offset_pitch_orig));
  free_string_field (&(args_info->test_mode_orig));
  
  

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, const char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->detailed_help_given)
    write_into_file(outfile, "detailed-help", 0, 0 );
  if (args_info->full_help_given)
    write_into_file(outfile, "full-help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->config_file_given)
    write_into_file(outfile, "config-file", args_info->config_file_orig, 0);
  if (args_info->output_file_given)
    write_into_file(outfile, "output-file", args_info->output_file_orig, 0);
  if (args_info->gpx_file_given)
    write_into_file(outfile, "gpx-file", args_info->gpx_file_orig, 0);
  if (args_info->output_file_date_given)
    write_into_file(outfile, "output-file-date", 0, 0 );
  if (args_info->output_file_format_given)
    write_into_file(outfile, "output-file-format", args_info->output_file_format_orig, 0);
  if (args_info->gear_ratios_given)
    write_into_file(outfile, "gear-ratios", args_info->gear_ratios_orig, 0);
  if (args_info->weight_given)
    write_into_file(outfile, "weight", args_info->weight_orig, 0);
  write_multiple_into_file(outfile, args_info->v_given, "v", 0, 0);
  if (args_info->verbose_given)
    write_into_file(outfile, "verbose", args_info->verbose_orig, cmdline_parser_verbose_values);
  if (args_info->quiet_given)
    write_into_file(outfile, "quiet", 0, 0 );
  if (args_info->front_controls_given)
    write_into_file(outfile, "front-controls", args_info->front_controls_orig, 0);
  if (args_info->ignitech_given)
    write_into_file(outfile, "ignitech", args_info->ignitech_orig, 0);
  if (args_info->lc2_given)
    write_into_file(outfile, "lc2", args_info->lc2_orig, 0);
  if (args_info->lc2_delay_given)
    write_into_file(outfile, "lc2-delay", args_info->lc2_delay_orig, 0);
  if (args_info->lc2_pin_given)
    write_into_file(outfile, "lc2-pin", args_info->lc2_pin_orig, 0);
  if (args_info->sleepy_given)
    write_into_file(outfile, "sleepy", args_info->sleepy_orig, 0);
  if (args_info->sleepy_addr_given)
    write_into_file(outfile, "sleepy-addr", args_info->sleepy_addr_orig, 0);
  if (args_info->can_given)
    write_into_file(outfile, "can", args_info->can_orig, 0);
  if (args_info->ignitech_dump_file_given)
    write_into_file(outfile, "ignitech-dump-file", args_info->ignitech_dump_file_orig, 0);
  if (args_info->ignitech_servo_as_iap_given)
    write_into_file(outfile, "ignitech-servo-as-iap", 0, 0 );
  if (args_info->ignitech_sai_low_given)
    write_into_file(outfile, "ignitech-sai-low", args_info->ignitech_sai_low_orig, 0);
  if (args_info->ignitech_sai_low_mv_given)
    write_into_file(outfile, "ignitech-sai-low-mv", args_info->ignitech_sai_low_mv_orig, 0);
  if (args_info->ignitech_sai_high_given)
    write_into_file(outfile, "ignitech-sai-high", args_info->ignitech_sai_high_orig, 0);
  if (args_info->ignitech_sai_high_mv_given)
    write_into_file(outfile, "ignitech-sai-high-mv", args_info->ignitech_sai_high_mv_orig, 0);
  if (args_info->mount_offset_roll_given)
    write_into_file(outfile, "mount-offset-roll", args_info->mount_offset_roll_orig, 0);
  if (args_info->mount_offset_pitch_given)
    write_into_file(outfile, "mount-offset-pitch", args_info->mount_offset_pitch_orig, 0);
  if (args_info->roll_pitch_swap_given)
    write_into_file(outfile, "roll-pitch-swap", 0, 0 );
  if (args_info->test_mode_given)
    write_into_file(outfile, "test-mode", args_info->test_mode_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc)
{
  int error_occurred = 0;

  if (option_given && (min > 0 || max > 0))
    {
      if (min > 0 && max > 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != (unsigned int) min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error_occurred = 1;
                }
            }
          else if (option_given < (unsigned int) min
                || option_given > (unsigned int) max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error_occurred = 1;
            }
        }
      else if (min > 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error_occurred = 1;
            }
        }
      else if (max > 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error_occurred = 1;
            }
        }
    }
    
  return error_occurred;
}
int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->v_given, args_info->v_min, args_info->v_max, "'--v' ('-v')"))
     error_occurred = 1;
  
  
  /* checks for dependences among options */
  if (args_info->output_file_given && ! args_info->output_file_format_given)
    {
      fprintf (stderr, "%s: '--output-file' ('-o') option depends on option 'output-file-format'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->output_file_format_given && ! args_info->output_file_given)
    {
      fprintf (stderr, "%s: '--output-file-format' option depends on option 'output-file'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->lc2_delay_given && ! args_info->lc2_given)
    {
      fprintf (stderr, "%s: '--lc2-delay' option depends on option 'lc2'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->lc2_pin_given && ! args_info->lc2_given)
    {
      fprintf (stderr, "%s: '--lc2-pin' option depends on option 'lc2'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->sleepy_addr_given && ! args_info->sleepy_given)
    {
      fprintf (stderr, "%s: '--sleepy-addr' option depends on option 'sleepy'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->ignitech_dump_file_given && ! args_info->ignitech_given)
    {
      fprintf (stderr, "%s: '--ignitech-dump-file' option depends on option 'ignitech'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->ignitech_servo_as_iap_given && ! args_info->ignitech_sai_low_given)
    {
      fprintf (stderr, "%s: '--ignitech-servo-as-iap' option depends on option 'ignitech-sai-low'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->ignitech_sai_low_given && ! args_info->ignitech_sai_low_mv_given)
    {
      fprintf (stderr, "%s: '--ignitech-sai-low' option depends on option 'ignitech-sai-low-mv'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->ignitech_sai_low_mv_given && ! args_info->ignitech_sai_high_given)
    {
      fprintf (stderr, "%s: '--ignitech-sai-low-mv' option depends on option 'ignitech-sai-high'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->ignitech_sai_high_given && ! args_info->ignitech_sai_high_mv_given)
    {
      fprintf (stderr, "%s: '--ignitech-sai-high' option depends on option 'ignitech-sai-high-mv'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->ignitech_sai_high_mv_given && ! args_info->ignitech_given)
    {
      fprintf (stderr, "%s: '--ignitech-sai-high-mv' option depends on option 'ignitech'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->mount_offset_roll_given && ! args_info->can_given)
    {
      fprintf (stderr, "%s: '--mount-offset-roll' option depends on option 'can'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->mount_offset_pitch_given && ! args_info->can_given)
    {
      fprintf (stderr, "%s: '--mount-offset-pitch' option depends on option 'can'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->roll_pitch_swap_given && ! args_info->can_given)
    {
      fprintf (stderr, "%s: '--roll-pitch-swap' option depends on option 'can'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_ENUM:
    if (val) *((int *)field) = found;
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_FLOAT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "detailed-help",	0, NULL, 0 },
        { "full-help",	0, NULL, 0 },
        { "version",	0, NULL, 'V' },
        { "config-file",	1, NULL, 'c' },
        { "output-file",	1, NULL, 'o' },
        { "gpx-file",	1, NULL, 'G' },
        { "output-file-date",	0, NULL, 'd' },
        { "output-file-format",	1, NULL, 0 },
        { "gear-ratios",	1, NULL, 'g' },
        { "weight",	1, NULL, 'W' },
        { "v",	0, NULL, 'v' },
        { "verbose",	1, NULL, 0 },
        { "quiet",	0, NULL, 'q' },
        { "front-controls",	1, NULL, 'f' },
        { "ignitech",	1, NULL, 'i' },
        { "lc2",	1, NULL, 'l' },
        { "lc2-delay",	1, NULL, 0 },
        { "lc2-pin",	1, NULL, 0 },
        { "sleepy",	1, NULL, 's' },
        { "sleepy-addr",	1, NULL, 0 },
        { "can",	1, NULL, 0 },
        { "ignitech-dump-file",	1, NULL, 0 },
        { "ignitech-servo-as-iap",	0, NULL, 0 },
        { "ignitech-sai-low",	1, NULL, 0 },
        { "ignitech-sai-low-mv",	1, NULL, 0 },
        { "ignitech-sai-high",	1, NULL, 0 },
        { "ignitech-sai-high-mv",	1, NULL, 0 },
        { "mount-offset-roll",	1, NULL, 0 },
        { "mount-offset-pitch",	1, NULL, 0 },
        { "roll-pitch-swap",	0, NULL, 0 },
        { "test-mode",	1, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVc:o:G:dg:W:vqf:i:l:s:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'c':	/* Configuration file..  */
        
        
          if (update_arg( (void *)&(args_info->config_file_arg), 
               &(args_info->config_file_orig), &(args_info->config_file_given),
              &(local_args_info.config_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "config-file", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Output file for CSV logging.  */
        
        
          if (update_arg( (void *)&(args_info->output_file_arg), 
               &(args_info->output_file_orig), &(args_info->output_file_given),
              &(local_args_info.output_file_given), optarg, 0, "/dev/null", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output-file", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'G':	/* Output file for GPX logging.  */
        
        
          if (update_arg( (void *)&(args_info->gpx_file_arg), 
               &(args_info->gpx_file_orig), &(args_info->gpx_file_given),
              &(local_args_info.gpx_file_given), optarg, 0, "/dev/null", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "gpx-file", 'G',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Insert date and time into output filename..  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->output_file_date_given),
              &(local_args_info.output_file_date_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "output-file-date", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* RPM/Speed ratios. Comma separated. (Eg. -g \"175,122,95,78,67\").  */
        
        
          if (update_arg( (void *)&(args_info->gear_ratios_arg), 
               &(args_info->gear_ratios_orig), &(args_info->gear_ratios_given),
              &(local_args_info.gear_ratios_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "gear-ratios", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'W':	/* Weight of vehicle, in kg, to use for calculations..  */
        
        
          if (update_arg( (void *)&(args_info->weight_arg), 
               &(args_info->weight_orig), &(args_info->weight_given),
              &(local_args_info.weight_given), optarg, 0, "300", ARG_INT,
              check_ambiguity, override, 0, 0,
              "weight", 'W',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* Verbose output. Specify multiple times for increasing verbosity..  */
        
          local_args_info.v_given++;
        
          break;
        case 'q':	/* Suppress output. Same as --verbose=NONE (Overrides both -v and --verbose).  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->quiet_given),
              &(local_args_info.quiet_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "quiet", 'q',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* Front controls device.  */
        
        
          if (update_arg( (void *)&(args_info->front_controls_arg), 
               &(args_info->front_controls_orig), &(args_info->front_controls_given),
              &(local_args_info.front_controls_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "front-controls", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'i':	/* Ignitech ignition device.  */
        
        
          if (update_arg( (void *)&(args_info->ignitech_arg), 
               &(args_info->ignitech_orig), &(args_info->ignitech_given),
              &(local_args_info.ignitech_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "ignitech", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* Innovate LC-2 device.  */
        
        
          if (update_arg( (void *)&(args_info->lc2_arg), 
               &(args_info->lc2_orig), &(args_info->lc2_given),
              &(local_args_info.lc2_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "lc2", 'l',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* I2C device to communicate with Sleepy Pi..  */
        
        
          if (update_arg( (void *)&(args_info->sleepy_arg), 
               &(args_info->sleepy_orig), &(args_info->sleepy_given),
              &(local_args_info.sleepy_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "sleepy", 's',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          if (strcmp (long_options[option_index].name, "detailed-help") == 0) {
            cmdline_parser_print_detailed_help ();
            cmdline_parser_free (&local_args_info);
            exit (EXIT_SUCCESS);
          }

          if (strcmp (long_options[option_index].name, "full-help") == 0) {
            cmdline_parser_print_full_help ();
            cmdline_parser_free (&local_args_info);
            exit (EXIT_SUCCESS);
          }

          /* Format string of output CSV file.  */
          if (strcmp (long_options[option_index].name, "output-file-format") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->output_file_format_arg), 
                 &(args_info->output_file_format_orig), &(args_info->output_file_format_given),
                &(local_args_info.output_file_format_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "output-file-format", '-',
                additional_error))
              goto failure;
          
          }
          /* Set level of verbosity explicitly. 
          (Overrides -v)
.  */
          else if (strcmp (long_options[option_index].name, "verbose") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->verbose_arg), 
                 &(args_info->verbose_orig), &(args_info->verbose_given),
                &(local_args_info.verbose_given), optarg, cmdline_parser_verbose_values, "ERROR", ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "verbose", '-',
                additional_error))
              goto failure;
          
          }
          /* Delay before powering up LC-2..  */
          else if (strcmp (long_options[option_index].name, "lc2-delay") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->lc2_delay_arg), 
                 &(args_info->lc2_delay_orig), &(args_info->lc2_delay_given),
                &(local_args_info.lc2_delay_given), optarg, 0, "15", ARG_INT,
                check_ambiguity, override, 0, 0,
                "lc2-delay", '-',
                additional_error))
              goto failure;
          
          }
          /* GPIO pin that controls power for LC-2.  */
          else if (strcmp (long_options[option_index].name, "lc2-pin") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->lc2_pin_arg), 
                 &(args_info->lc2_pin_orig), &(args_info->lc2_pin_given),
                &(local_args_info.lc2_pin_given), optarg, 0, "26", ARG_INT,
                check_ambiguity, override, 0, 0,
                "lc2-pin", '-',
                additional_error))
              goto failure;
          
          }
          /* Address for Sleepy Pi..  */
          else if (strcmp (long_options[option_index].name, "sleepy-addr") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->sleepy_addr_arg), 
                 &(args_info->sleepy_addr_orig), &(args_info->sleepy_addr_given),
                &(local_args_info.sleepy_addr_given), optarg, 0, "0x04", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "sleepy-addr", '-',
                additional_error))
              goto failure;
          
          }
          /* CAN device to bind to. CAN disabled if not set..  */
          else if (strcmp (long_options[option_index].name, "can") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->can_arg), 
                 &(args_info->can_orig), &(args_info->can_given),
                &(local_args_info.can_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "can", '-',
                additional_error))
              goto failure;
          
          }
          /* File to dump raw responses from Ignitech.  */
          else if (strcmp (long_options[option_index].name, "ignitech-dump-file") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->ignitech_dump_file_arg), 
                 &(args_info->ignitech_dump_file_orig), &(args_info->ignitech_dump_file_given),
                &(local_args_info.ignitech_dump_file_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "ignitech-dump-file", '-',
                additional_error))
              goto failure;
          
          }
          /* Treat servo reading as IAP. Requires calibration options..  */
          else if (strcmp (long_options[option_index].name, "ignitech-servo-as-iap") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->ignitech_servo_as_iap_flag), 0, &(args_info->ignitech_servo_as_iap_given),
                &(local_args_info.ignitech_servo_as_iap_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "ignitech-servo-as-iap", '-',
                additional_error))
              goto failure;
          
          }
          /* Low kpa reading. Eg: 21.  */
          else if (strcmp (long_options[option_index].name, "ignitech-sai-low") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->ignitech_sai_low_arg), 
                 &(args_info->ignitech_sai_low_orig), &(args_info->ignitech_sai_low_given),
                &(local_args_info.ignitech_sai_low_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "ignitech-sai-low", '-',
                additional_error))
              goto failure;
          
          }
          /* Low mv value. Eg: 708.  */
          else if (strcmp (long_options[option_index].name, "ignitech-sai-low-mv") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->ignitech_sai_low_mv_arg), 
                 &(args_info->ignitech_sai_low_mv_orig), &(args_info->ignitech_sai_low_mv_given),
                &(local_args_info.ignitech_sai_low_mv_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "ignitech-sai-low-mv", '-',
                additional_error))
              goto failure;
          
          }
          /* High kpa reading. Eg: 102.  */
          else if (strcmp (long_options[option_index].name, "ignitech-sai-high") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->ignitech_sai_high_arg), 
                 &(args_info->ignitech_sai_high_orig), &(args_info->ignitech_sai_high_given),
                &(local_args_info.ignitech_sai_high_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "ignitech-sai-high", '-',
                additional_error))
              goto failure;
          
          }
          /* High mv value. Eg: 4252.  */
          else if (strcmp (long_options[option_index].name, "ignitech-sai-high-mv") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->ignitech_sai_high_mv_arg), 
                 &(args_info->ignitech_sai_high_mv_orig), &(args_info->ignitech_sai_high_mv_given),
                &(local_args_info.ignitech_sai_high_mv_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "ignitech-sai-high-mv", '-',
                additional_error))
              goto failure;
          
          }
          /* Offset to zero imu reading.  */
          else if (strcmp (long_options[option_index].name, "mount-offset-roll") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->mount_offset_roll_arg), 
                 &(args_info->mount_offset_roll_orig), &(args_info->mount_offset_roll_given),
                &(local_args_info.mount_offset_roll_given), optarg, 0, 0, ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "mount-offset-roll", '-',
                additional_error))
              goto failure;
          
          }
          /* Offset to zero imu reading.  */
          else if (strcmp (long_options[option_index].name, "mount-offset-pitch") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->mount_offset_pitch_arg), 
                 &(args_info->mount_offset_pitch_orig), &(args_info->mount_offset_pitch_given),
                &(local_args_info.mount_offset_pitch_given), optarg, 0, 0, ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "mount-offset-pitch", '-',
                additional_error))
              goto failure;
          
          }
          /* Swap roll and pitch. Used depending on physical sensor orientation..  */
          else if (strcmp (long_options[option_index].name, "roll-pitch-swap") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->roll_pitch_swap_flag), 0, &(args_info->roll_pitch_swap_given),
                &(local_args_info.roll_pitch_swap_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "roll-pitch-swap", '-',
                additional_error))
              goto failure;
          
          }
          /* Secret test mode. Does not continue running.  */
          else if (strcmp (long_options[option_index].name, "test-mode") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->test_mode_arg), 
                 &(args_info->test_mode_orig), &(args_info->test_mode_given),
                &(local_args_info.test_mode_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "test-mode", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  args_info->v_given += local_args_info.v_given;
  local_args_info.v_given = 0;
  
  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}

#ifndef CONFIG_FILE_LINE_SIZE
#define CONFIG_FILE_LINE_SIZE 2048
#endif
#define ADDITIONAL_ERROR " in configuration file "

#define CONFIG_FILE_LINE_BUFFER_SIZE (CONFIG_FILE_LINE_SIZE+3)
/* 3 is for "--" and "=" */

static int
_cmdline_parser_configfile (const char *filename, int *my_argc)
{
  FILE* file;
  char my_argv[CONFIG_FILE_LINE_BUFFER_SIZE+1];
  char linebuf[CONFIG_FILE_LINE_SIZE];
  int line_num = 0;
  int result = 0, equal;
  char *fopt, *farg;
  char *str_index;
  size_t len, next_token;
  char delimiter;

  if ((file = fopen(filename, "r")) == 0)
    {
      fprintf (stderr, "%s: Error opening configuration file '%s'\n",
               CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  while ((fgets(linebuf, CONFIG_FILE_LINE_SIZE, file)) != 0)
    {
      ++line_num;
      my_argv[0] = '\0';
      len = strlen(linebuf);
      if (len > (CONFIG_FILE_LINE_BUFFER_SIZE-1))
        {
          fprintf (stderr, "%s:%s:%d: Line too long in configuration file\n",
                   CMDLINE_PARSER_PACKAGE, filename, line_num);
          result = EXIT_FAILURE;
          break;
        }

      /* find first non-whitespace character in the line */
      next_token = strspn (linebuf, " \t\r\n");
      str_index  = linebuf + next_token;

      if ( str_index[0] == '\0' || str_index[0] == '#')
        continue; /* empty line or comment line is skipped */

      fopt = str_index;

      /* truncate fopt at the end of the first non-valid character */
      next_token = strcspn (fopt, " \t\r\n=");

      if (fopt[next_token] == '\0') /* the line is over */
        {
          farg  = 0;
          equal = 0;
          goto noarg;
        }

      /* remember if equal sign is present */
      equal = (fopt[next_token] == '=');
      fopt[next_token++] = '\0';

      /* advance pointers to the next token after the end of fopt */
      next_token += strspn (fopt + next_token, " \t\r\n");

      /* check for the presence of equal sign, and if so, skip it */
      if ( !equal )
        if ((equal = (fopt[next_token] == '=')))
          {
            next_token++;
            next_token += strspn (fopt + next_token, " \t\r\n");
          }
      str_index  += next_token;

      /* find argument */
      farg = str_index;
      if ( farg[0] == '\"' || farg[0] == '\'' )
        { /* quoted argument */
          str_index = strchr (++farg, str_index[0] ); /* skip opening quote */
          if (! str_index)
            {
              fprintf
                (stderr,
                 "%s:%s:%d: unterminated string in configuration file\n",
                 CMDLINE_PARSER_PACKAGE, filename, line_num);
              result = EXIT_FAILURE;
              break;
            }
        }
      else
        { /* read up the remaining part up to a delimiter */
          next_token = strcspn (farg, " \t\r\n#\'\"");
          str_index += next_token;
        }

      /* truncate farg at the delimiter and store it for further check */
      delimiter = *str_index, *str_index++ = '\0';

      /* everything but comment is illegal at the end of line */
      if (delimiter != '\0' && delimiter != '#')
        {
          str_index += strspn(str_index, " \t\r\n");
          if (*str_index != '\0' && *str_index != '#')
            {
              fprintf
                (stderr,
                 "%s:%s:%d: malformed string in configuration file\n",
                 CMDLINE_PARSER_PACKAGE, filename, line_num);
              result = EXIT_FAILURE;
              break;
            }
        }

    noarg:
      if (!strcmp(fopt,"include")) {
        if (farg && *farg) {
          result = _cmdline_parser_configfile(farg, my_argc);
        } else {
          fprintf(stderr, "%s:%s:%d: include requires a filename argument.\n",
                  CMDLINE_PARSER_PACKAGE, filename, line_num);
        }
        continue;
      }
      len = strlen(fopt);
      strcat (my_argv, len > 1 ? "--" : "-");
      strcat (my_argv, fopt);
      if (len > 1 && ((farg && *farg) || equal))
        strcat (my_argv, "=");
      if (farg && *farg)
        strcat (my_argv, farg);
      ++(*my_argc);

      cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
      cmd_line_list_tmp->next = cmd_line_list;
      cmd_line_list = cmd_line_list_tmp;
      cmd_line_list->string_arg = gengetopt_strdup(my_argv);
    } /* while */

  if (file)
    fclose(file);
  return result;
}

int
cmdline_parser_configfile (
  const char *filename,
                           struct gengetopt_args_info *args_info,
                           int override, int initialize, int check_required)
{
  struct cmdline_parser_params params;

  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;
  
  return cmdline_parser_config_file (filename, args_info, &params);
}

int
cmdline_parser_config_file (const char *filename,
                           struct gengetopt_args_info *args_info,
                           struct cmdline_parser_params *params)
{
  int i, result;
  int my_argc = 1;
  char **my_argv_arg;
  char *additional_error;

  /* store the program name */
  cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
  cmd_line_list_tmp->next = cmd_line_list;
  cmd_line_list = cmd_line_list_tmp;
  cmd_line_list->string_arg = gengetopt_strdup (CMDLINE_PARSER_PACKAGE);

  result = _cmdline_parser_configfile(filename, &my_argc);

  if (result != EXIT_FAILURE) {
    my_argv_arg = (char **) malloc((my_argc+1) * sizeof(char *));
    cmd_line_list_tmp = cmd_line_list;

    for (i = my_argc - 1; i >= 0; --i) {
      my_argv_arg[i] = cmd_line_list_tmp->string_arg;
      cmd_line_list_tmp = cmd_line_list_tmp->next;
    }

    my_argv_arg[my_argc] = 0;

    additional_error = (char *)malloc(strlen(filename) + strlen(ADDITIONAL_ERROR) + 1);
    strcpy (additional_error, ADDITIONAL_ERROR);
    strcat (additional_error, filename);
    result =
      cmdline_parser_internal (my_argc, my_argv_arg, args_info,
                              params,
                              additional_error);

    free (additional_error);
    free (my_argv_arg);
  }

  free_cmd_list();
  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}
/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
