/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 37.2.0 Fri Aug 16 11:11:00 2024.
 */

#include <string.h>

#include "edl.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int edl_edl_pack(
    uint8_t *dst_p,
    const struct edl_edl_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[3] |= pack_left_shift_u8(src_p->cmd_a, 0u, 0xffu);

    return (4);
}

int edl_edl_unpack(
    struct edl_edl_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->cmd_a = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

uint8_t edl_edl_cmd_a_encode(double value)
{
    return (uint8_t)(value);
}

double edl_edl_cmd_a_decode(uint8_t value)
{
    return ((double)value);
}

bool edl_edl_cmd_a_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int edl_engine1_pack(
    uint8_t *dst_p,
    const struct edl_engine1_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rpm, 8u, 0x3fu);
    dst_p[2] |= pack_left_shift_u8(src_p->speed_mph, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->oil_pres, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->oil_temp, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->oil_temp, 8u, 0x01u);
    dst_p[6] |= pack_left_shift_u8(src_p->voltage, 0u, 0xffu);

    return (7);
}

int edl_engine1_unpack(
    struct edl_engine1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rpm |= unpack_left_shift_u16(src_p[1], 8u, 0x3fu);
    dst_p->speed_mph = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->oil_pres = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->oil_temp = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->oil_temp |= unpack_left_shift_u16(src_p[5], 8u, 0x01u);
    dst_p->voltage = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

uint16_t edl_engine1_rpm_encode(double value)
{
    return (uint16_t)(value);
}

double edl_engine1_rpm_decode(uint16_t value)
{
    return ((double)value);
}

bool edl_engine1_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t edl_engine1_speed_mph_encode(double value)
{
    return (uint8_t)(value);
}

double edl_engine1_speed_mph_decode(uint8_t value)
{
    return ((double)value);
}

bool edl_engine1_speed_mph_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t edl_engine1_oil_pres_encode(double value)
{
    return (uint8_t)(value);
}

double edl_engine1_oil_pres_decode(uint8_t value)
{
    return ((double)value);
}

bool edl_engine1_oil_pres_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t edl_engine1_oil_temp_encode(double value)
{
    return (uint16_t)(value - -50.0);
}

double edl_engine1_oil_temp_decode(uint16_t value)
{
    return ((double)value + -50.0);
}

bool edl_engine1_oil_temp_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

uint8_t edl_engine1_voltage_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double edl_engine1_voltage_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool edl_engine1_voltage_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int edl_engine2_pack(
    uint8_t *dst_p,
    const struct edl_engine2_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u32(src_p->odo, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->odo, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->odo, 16u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->trip, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->trip, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->trip, 16u, 0x0fu);

    return (6);
}

int edl_engine2_unpack(
    struct edl_engine2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->odo = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->odo |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->odo |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->trip = unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->trip |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    dst_p->trip |= unpack_left_shift_u32(src_p[5], 16u, 0x0fu);

    return (0);
}

uint32_t edl_engine2_odo_encode(double value)
{
    return (uint32_t)(value / 0.1);
}

double edl_engine2_odo_decode(uint32_t value)
{
    return ((double)value * 0.1);
}

bool edl_engine2_odo_is_in_range(uint32_t value)
{
    return (value <= 16777210u);
}

uint32_t edl_engine2_trip_encode(double value)
{
    return (uint32_t)(value / 0.1);
}

double edl_engine2_trip_decode(uint32_t value)
{
    return ((double)value * 0.1);
}

bool edl_engine2_trip_is_in_range(uint32_t value)
{
    return (value <= 1048570u);
}

int edl_engine3_pack(
    uint8_t *dst_p,
    const struct edl_engine3_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u8(src_p->adv, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->tps, 0u, 0x7fu);
    dst_p[2] |= pack_left_shift_u8(src_p->iap, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->gear, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->lambda, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->lambda, 8u, 0x0fu);

    return (6);
}

int edl_engine3_unpack(
    struct edl_engine3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->adv = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->tps = unpack_right_shift_u8(src_p[1], 0u, 0x7fu);
    dst_p->iap = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->gear = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->lambda = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->lambda |= unpack_left_shift_u16(src_p[5], 8u, 0x0fu);

    return (0);
}

uint8_t edl_engine3_adv_encode(double value)
{
    return (uint8_t)(value);
}

double edl_engine3_adv_decode(uint8_t value)
{
    return ((double)value);
}

bool edl_engine3_adv_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t edl_engine3_tps_encode(double value)
{
    return (uint8_t)(value);
}

double edl_engine3_tps_decode(uint8_t value)
{
    return ((double)value);
}

bool edl_engine3_tps_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t edl_engine3_iap_encode(double value)
{
    return (uint8_t)(value);
}

double edl_engine3_iap_decode(uint8_t value)
{
    return ((double)value);
}

bool edl_engine3_iap_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t edl_engine3_gear_encode(double value)
{
    return (uint8_t)(value);
}

double edl_engine3_gear_decode(uint8_t value)
{
    return ((double)value);
}

bool edl_engine3_gear_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t edl_engine3_lambda_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double edl_engine3_lambda_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool edl_engine3_lambda_is_in_range(uint16_t value)
{
    return (value <= 3400u);
}
