/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 37.0.7 Sun Jun  5 21:40:10 2022.
 */

#ifndef IGNITECH_CAN_H
#define IGNITECH_CAN_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define IGNITECH_CAN_IGNITECH_WB_2_FRAME_ID (0x322u)

/* Frame lengths in bytes. */
#define IGNITECH_CAN_IGNITECH_WB_2_LENGTH (8u)

/* Extended or standard frame types. */
#define IGNITECH_CAN_IGNITECH_WB_2_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/**
 * Signals in message Ignitech_WB_2.
 *
 * All signal values are as on the CAN bus.
 */
struct ignitech_can_ignitech_wb_2_t {
  /**
   * Range: 0..10000 (0..100.00 -)
   * Scale: 0.01
   * Offset: 0
   */
  uint16_t lambda;
};

/**
 * Pack message Ignitech_WB_2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ignitech_can_ignitech_wb_2_pack(
  uint8_t *dst_p,
  const struct ignitech_can_ignitech_wb_2_t *src_p,
  size_t size);

/**
 * Unpack message Ignitech_WB_2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ignitech_can_ignitech_wb_2_unpack(
  struct ignitech_can_ignitech_wb_2_t *dst_p,
  const uint8_t *src_p,
  size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ignitech_can_ignitech_wb_2_lambda_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ignitech_can_ignitech_wb_2_lambda_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ignitech_can_ignitech_wb_2_lambda_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
