/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 37.0.7 Sun Jun  5 20:48:55 2022.
 */

#include <string.h>

#include "imu_can.h"

static inline uint8_t pack_left_shift_u16(
  uint16_t value,
  uint8_t shift,
  uint8_t mask)
{
  return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
  uint16_t value,
  uint8_t shift,
  uint8_t mask)
{
  return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
  uint8_t value,
  uint8_t shift,
  uint8_t mask)
{
  return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
  uint8_t value,
  uint8_t shift,
  uint8_t mask)
{
  return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int imu_can_body_position_pack(
  uint8_t *dst_p,
  const struct imu_can_body_position_t *src_p,
  size_t size)
{
  if (size < 8u) {
    return (-EINVAL);
  }

  memset(&dst_p[0], 0, 8);

  dst_p[0] |= pack_left_shift_u16(src_p->roll_angle, 0u, 0xffu);
  dst_p[1] |= pack_right_shift_u16(src_p->roll_angle, 8u, 0x0fu);
  dst_p[1] |= pack_left_shift_u16(src_p->pitch_angle, 4u, 0xf0u);
  dst_p[2] |= pack_right_shift_u16(src_p->pitch_angle, 4u, 0xffu);

  return (8);
}

int imu_can_body_position_unpack(
  struct imu_can_body_position_t *dst_p,
  const uint8_t *src_p,
  size_t size)
{
  if (size < 8u) {
    return (-EINVAL);
  }

  dst_p->roll_angle = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
  dst_p->roll_angle |= unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
  dst_p->pitch_angle = unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
  dst_p->pitch_angle |= unpack_left_shift_u16(src_p[2], 4u, 0xffu);

  return (0);
}

uint16_t imu_can_body_position_roll_angle_encode(double value)
{
  return (uint16_t)((value - -180.0) / 0.1);
}

double imu_can_body_position_roll_angle_decode(uint16_t value)
{
  return (((double)value * 0.1) + -180.0);
}

bool imu_can_body_position_roll_angle_is_in_range(uint16_t value)
{
  return (value <= 3600u);
}

uint16_t imu_can_body_position_pitch_angle_encode(double value)
{
  return (uint16_t)((value - -180.0) / 0.1);
}

double imu_can_body_position_pitch_angle_decode(uint16_t value)
{
  return (((double)value * 0.1) + -180.0);
}

bool imu_can_body_position_pitch_angle_is_in_range(uint16_t value)
{
  return (value <= 3600u);
}
