/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.5 Sat Jul 20 18:08:30 2024.
 */

#ifndef SPARTAN3_H
#define SPARTAN3_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define SPARTAN3_SPARTAN3_FRAME_ID (0x400u)

/* Frame lengths in bytes. */
#define SPARTAN3_SPARTAN3_LENGTH (4u)

/* Extended or standard frame types. */
#define SPARTAN3_SPARTAN3_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define SPARTAN3_SPARTAN3_STATUS_RESERVED_0_CHOICE (0u)
#define SPARTAN3_SPARTAN3_STATUS_WAITING_TO_HEAT_UP_CHOICE (1u)
#define SPARTAN3_SPARTAN3_STATUS_HEATING_UP_CHOICE (2u)
#define SPARTAN3_SPARTAN3_STATUS_NORMAL_OPERATION_CHOICE (3u)
#define SPARTAN3_SPARTAN3_STATUS_RESERVED_4_CHOICE (4u)

/* Frame Names. */
#define SPARTAN3_SPARTAN3_NAME "SPARTAN3"

/* Signal Names. */
#define SPARTAN3_SPARTAN3_LAMBDA_NAME "LAMBDA"
#define SPARTAN3_SPARTAN3_LSU_TEMP_NAME "LSU_TEMP"
#define SPARTAN3_SPARTAN3_STATUS_NAME "STATUS"

/**
 * Signals in message SPARTAN3.
 *
 * All signal values are as on the CAN bus.
 */
struct spartan3_spartan3_t {
  /**
   * Range: 0..3400 (0..3.4 -)
   * Scale: 0.001
   * Offset: 0
   */
  uint16_t lambda;

  /**
   * Range: 0..250 (0..2500 F)
   * Scale: 10
   * Offset: 0
   */
  uint8_t lsu_temp;

  /**
   * Range: 0..255 (0..255 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t status;
};

/**
 * Pack message SPARTAN3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int spartan3_spartan3_pack(
  uint8_t *dst_p,
  const struct spartan3_spartan3_t *src_p,
  size_t size);

/**
 * Unpack message SPARTAN3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int spartan3_spartan3_unpack(
  struct spartan3_spartan3_t *dst_p,
  const uint8_t *src_p,
  size_t size);

/**
 * Init message fields to default values from SPARTAN3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int spartan3_spartan3_init(struct spartan3_spartan3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t spartan3_spartan3_lambda_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double spartan3_spartan3_lambda_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool spartan3_spartan3_lambda_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t spartan3_spartan3_lsu_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double spartan3_spartan3_lsu_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool spartan3_spartan3_lsu_temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t spartan3_spartan3_status_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double spartan3_spartan3_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool spartan3_spartan3_status_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
