/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.5 Sat Jul 20 18:08:30 2024.
 */

#include <string.h>

#include "spartan3.h"

static inline uint8_t pack_left_shift_u8(
  uint8_t value,
  uint8_t shift,
  uint8_t mask)
{
  return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
  uint16_t value,
  uint8_t shift,
  uint8_t mask)
{
  return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
  uint16_t value,
  uint8_t shift,
  uint8_t mask)
{
  return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
  uint8_t value,
  uint8_t shift,
  uint8_t mask)
{
  return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
  uint8_t value,
  uint8_t shift,
  uint8_t mask)
{
  return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
  uint8_t value,
  uint8_t shift,
  uint8_t mask)
{
  return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int spartan3_spartan3_pack(
  uint8_t *dst_p,
  const struct spartan3_spartan3_t *src_p,
  size_t size)
{
  if (size < 4u) {
    return (-EINVAL);
  }

  memset(&dst_p[0], 0, 4);

  dst_p[0] |= pack_right_shift_u16(src_p->lambda, 8u, 0xffu);
  dst_p[1] |= pack_left_shift_u16(src_p->lambda, 0u, 0xffu);
  dst_p[2] |= pack_left_shift_u8(src_p->lsu_temp, 0u, 0xffu);
  dst_p[3] |= pack_left_shift_u8(src_p->status, 0u, 0xffu);

  return (4);
}

int spartan3_spartan3_unpack(
  struct spartan3_spartan3_t *dst_p,
  const uint8_t *src_p,
  size_t size)
{
  if (size < 4u) {
    return (-EINVAL);
  }

  dst_p->lambda = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
  dst_p->lambda |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
  dst_p->lsu_temp = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
  dst_p->status = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

  return (0);
}

int spartan3_spartan3_init(struct spartan3_spartan3_t *msg_p)
{
  if (msg_p == NULL) return -1;

  memset(msg_p, 0, sizeof(struct spartan3_spartan3_t));

  return 0;
}

uint16_t spartan3_spartan3_lambda_encode(double value)
{
  return (uint16_t)(value / 0.001);
}

double spartan3_spartan3_lambda_decode(uint16_t value)
{
  return ((double)value * 0.001);
}

bool spartan3_spartan3_lambda_is_in_range(uint16_t value)
{
  return (value <= 3400u);
}

uint8_t spartan3_spartan3_lsu_temp_encode(double value)
{
  return (uint8_t)(value / 10.0);
}

double spartan3_spartan3_lsu_temp_decode(uint8_t value)
{
  return ((double)value * 10.0);
}

bool spartan3_spartan3_lsu_temp_is_in_range(uint8_t value)
{
  return (value <= 250u);
}

uint8_t spartan3_spartan3_status_encode(double value)
{
  return (uint8_t)(value);
}

double spartan3_spartan3_status_decode(uint8_t value)
{
  return ((double)value);
}

bool spartan3_spartan3_status_is_in_range(uint8_t value)
{
  (void)value;

  return (true);
}
