name: C/C++ CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libIgnitech
      run: |
        ./install-deps.sh ignitech
    - name: Install libISP2
      run: |
        ./install-deps.sh isp
    - name: Install Bluetooth headers
      run: ./install-deps.sh bluetooth
    - name: Install Flatbuffers
      run: |
        ./install-deps.sh flatbuffers
    - name: Install bcm2835lib
      run: |
        ./install-deps.sh bcm2835
    - name: configure
      run: ./configure --disable-can --without-bcm2835
    - name: make
      run: make
    - name: Install utilities for tests
      run: sudo apt install can-utils
    - name: make check
      run: sudo make check
    - name: Archive tests artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: test-logs
        path: |
          *.log
          tests/*.log
