name: C/C++ CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install libIgnitech
      run: |
        git clone https://github.com/techie66/libIgnitech.git
        cd libIgnitech
        ./autogen.sh
        ./configure
        make
        sudo make install
        cd ..
    - name: Install libISP2
      run: |
        git clone https://github.com/techie66/libISP2.git
        cd libISP2
        ./autogen.sh
        ./configure
        make
        sudo make install
        cd ..
    - name: Install Bluetooth headers
      run: sudo apt-get install libbluetooth-dev
    - name: Install Flatbuffers
      run: |
        git clone https://github.com/google/flatbuffers.git
        cd flatbuffers
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
        make
        sudo make install
        cd ..
    - name: Install bcm2835lib
      run: |
        wget http://www.airspayce.com/mikem/bcm2835/bcm2835-1.68.tar.gz
        tar -xf bcm2835-1.68.tar.gz
        cd bcm2835-1.68
        ./configure
        make
        sudo make install
        cd ..
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
