name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Flatbuffers
      run: |
        cd ..
        git clone https://github.com/google/flatbuffers.git
        cd flatbuffers
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
        make
        make install
        cd ../EngineDataLogger
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
